const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.Touch,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.bound,
		C3.Behaviors.EightDir,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Behaviors.Tween,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{平鋪圖: 0},
	{實體: 0},
	{遊戲開始按鈕: 0},
	{觸控: 0},
	{灰貓: 0},
	{橘貓: 0},
	{平鋪圖2: 0},
	{精靈2: 0},
	{InpCatName: 0},
	{確認按鈕: 0},
	{文本: 0},
	{平鋪圖3: 0},
	{CANALICK: 0},
	{正弦運動: 0},
	{逗貓棒: 0},
	{isCorrect: 0},
	{CanClick: 0},
	{飼料: 0},
	{canclick: 0},
	{精靈: 0},
	{精靈3: 0},
	{文本2: 0},
	{精靈4: 0},
	{文本3: 0},
	{startX: 0},
	{starty: 0},
	{拖放: 0},
	{精靈6: 0},
	{精靈10: 0},
	{文本4: 0},
	{精靈5: 0},
	{邊界約束: 0},
	{八方向: 0},
	{精靈7: 0},
	{子彈: 0},
	{精靈8: 0},
	{精靈9: 0},
	{精靈11: 0},
	{精靈12: 0},
	{hp: 0},
	{timer: 0},
	{淡入淡出: 0},
	{文本5: 0},
	{這個不能吃: 0},
	{平鋪圖4: 0},
	{平鋪圖5: 0},
	{補間動畫: 0},
	{精靈13: 0},
	{滑鼠: 0},
	{精靈14: 0},
	{精靈15: 0},
	{shittimer: 0},
	{shitscore: 0},
	{文本6: 0},
	{精靈16: 0},
	{灰貓順毛上翹: 0},
	{炸毛上翹: 0},
	{精靈17: 0},
	{文本7: 0},
	{文本8: 0},
	{文本9: 0},
	{文本10: 0},
	{文本11: 0},
	{文本12: 0},
	{開心: 0},
	{害怕: 0},
	{生氣: 0},
	{txtRules3: 0},
	{情緒文字框: 0},
	{吃東西文字框: 0},
	{精靈18: 0},
	{答錯: 0},
	{精靈19: 0},
	{txtDialogue: 0},
	{精靈20: 0},
	{文本13: 0},
	{前導框: 0},
	{文本14: 0},
	{精靈21: 0},
	{文本15: 0},
	{好了: 0},
	{鍵盤: 0},
	{精靈22: 0},
	{精靈23: 0},
	{ENDINGGG: 0},
	{文本16: 0},
	{精靈24: 0},
	{PlayerName: 0},
	{PlacedCount: 0},
	{HP: 0},
	{Timer: 0},
	{FirstTimeMistake: 0},
	{ChallengeSuccess: 0},
	{shhittimer: 0},
	{shitChallengeSuccess: 0},
	{EMOSCORE: 0},
	{EMOSUCCESS: 0},
	{DialogueIndex: 0},
	{ENDING: 0},
	{PlayerType: 0}
];

self.InstanceType = {
	平鋪圖: class extends self.ITiledBackgroundInstance {},
	遊戲開始按鈕: class extends self.ISpriteInstance {},
	觸控: class extends self.IInstance {},
	灰貓: class extends self.ISpriteInstance {},
	橘貓: class extends self.ISpriteInstance {},
	平鋪圖2: class extends self.ITiledBackgroundInstance {},
	精靈2: class extends self.ISpriteInstance {},
	InpCatName: class extends self.ITextInputInstance {},
	確認按鈕: class extends self.ISpriteInstance {},
	文本: class extends self.ITextInstance {},
	平鋪圖3: class extends self.ITiledBackgroundInstance {},
	逗貓棒: class extends self.ISpriteInstance {},
	飼料: class extends self.ISpriteInstance {},
	精靈: class extends self.ISpriteInstance {},
	精靈3: class extends self.ISpriteInstance {},
	文本2: class extends self.ITextInstance {},
	精靈4: class extends self.ISpriteInstance {},
	文本3: class extends self.ITextInstance {},
	精靈6: class extends self.ISpriteInstance {},
	精靈10: class extends self.ISpriteInstance {},
	文本4: class extends self.ITextInstance {},
	精靈5: class extends self.ISpriteInstance {},
	精靈7: class extends self.ISpriteInstance {},
	精靈8: class extends self.ISpriteInstance {},
	精靈9: class extends self.ISpriteInstance {},
	精靈11: class extends self.ISpriteInstance {},
	精靈12: class extends self.ISpriteInstance {},
	hp: class extends self.ITextInstance {},
	timer: class extends self.ITextInstance {},
	文本5: class extends self.ITextInstance {},
	這個不能吃: class extends self.ITextInstance {},
	平鋪圖4: class extends self.ITiledBackgroundInstance {},
	平鋪圖5: class extends self.ITiledBackgroundInstance {},
	精靈13: class extends self.ISpriteInstance {},
	滑鼠: class extends self.IInstance {},
	精靈14: class extends self.ISpriteInstance {},
	精靈15: class extends self.ISpriteInstance {},
	shittimer: class extends self.ITextInstance {},
	shitscore: class extends self.ITextInstance {},
	文本6: class extends self.ITextInstance {},
	精靈16: class extends self.ISpriteInstance {},
	灰貓順毛上翹: class extends self.ISpriteInstance {},
	炸毛上翹: class extends self.ISpriteInstance {},
	精靈17: class extends self.ISpriteInstance {},
	文本7: class extends self.ITextInstance {},
	文本8: class extends self.ITextInstance {},
	文本9: class extends self.ITextInstance {},
	文本10: class extends self.ITextInstance {},
	文本11: class extends self.ITextInstance {},
	文本12: class extends self.ITextInstance {},
	開心: class extends self.ISpriteInstance {},
	害怕: class extends self.ISpriteInstance {},
	生氣: class extends self.ISpriteInstance {},
	txtRules3: class extends self.ITextInstance {},
	情緒文字框: class extends self.ISpriteInstance {},
	吃東西文字框: class extends self.ISpriteInstance {},
	精靈18: class extends self.ISpriteInstance {},
	答錯: class extends self.IInstance {},
	精靈19: class extends self.ISpriteInstance {},
	txtDialogue: class extends self.ITextInstance {},
	精靈20: class extends self.ISpriteInstance {},
	文本13: class extends self.ITextInstance {},
	前導框: class extends self.ISpriteInstance {},
	文本14: class extends self.ITextInstance {},
	精靈21: class extends self.ISpriteInstance {},
	文本15: class extends self.ITextInstance {},
	好了: class extends self.ITextInstance {},
	鍵盤: class extends self.IInstance {},
	精靈22: class extends self.ISpriteInstance {},
	精靈23: class extends self.ISpriteInstance {},
	ENDINGGG: class extends self.ITextInstance {},
	文本16: class extends self.ITextInstance {},
	精靈24: class extends self.ISpriteInstance {}
}